//////////////////////////////////////////
//////////////////////////////////////////
// Generated by CodeGenerator
// Timestamp: 2026-03-01
//////////////////////////////////////////
//////////////////////////////////////////
using System;

namespace Data.Model.Models;

public class Systemconfiguration
{
    public string Systemgroup { get; set; }
    public string Paramgroup { get; set; }
    public string Paramident { get; set; }
    public string Paramvalue { get; set; }
    public string Paraminfo { get; set; }
    public string Paramtext { get; set; }
}
