using System.Data.Common;
using System.Text;
using Common.Extensions;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CodeGenerator.Library;

public class EntityGenerator
{
    private readonly ILogger _logger;
    private readonly IConfig _config;
    public EntityGenerator(ILogger logger, IConfig config)
    {
        _logger = logger;
        _config = config;
    }

    public void GenerateEntity(DbConnection connection, string tableName)
    {
        if (_config.DbType.IsEQ("sqlite"))
        {
            GenerateSQLiteEntity(connection, tableName);
        }
        else if (_config.DbType.IsEQ("sqlserver"))
        {
            GenerateMssqlEntity(connection, tableName);
        }
    }
    
    private void GenerateSQLiteEntity(DbConnection connection, string tableName)
    {
        var columns = new List<(string Name, string Type, bool Nullable, bool IsPrimaryKey)>();

        using var columnCmd = connection.CreateCommand();
        columnCmd.CommandText = $"PRAGMA table_info('{tableName}');";

        using var reader = columnCmd.ExecuteReader();
        while (reader.Read())
        {
            string name = reader["name"]?.ToString() ?? "";
            string type = reader["type"]?.ToString() ?? "";
            bool notNull = reader["notnull"]?.ToString() == "1";
            bool isPk = reader["pk"]?.ToString() == "1";

            columns.Add((name, type, !notNull, isPk));
        }

        GenerateDbContextFile(tableName);
        GenerateEntityClassFile(tableName, columns);
    }

    private void GenerateMssqlEntity(DbConnection connection, string tableName)
    {
        var columns = new List<(string Name, string Type, bool Nullable, bool IsPrimaryKey)>();

        using var columnCmd = connection.CreateCommand();
        columnCmd.CommandText = $@"
            SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, 
                   COLUMNPROPERTY(OBJECT_ID(TABLE_NAME), COLUMN_NAME, 'IsIdentity') AS IsPK
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = '{tableName}'";

        using var reader = columnCmd.ExecuteReader();
        while (reader.Read())
        {
            string name = reader["COLUMN_NAME"]?.ToString() ?? "";
            string type = reader["DATA_TYPE"]?.ToString() ?? "";
            bool nullable = reader["IS_NULLABLE"]?.ToString() == "YES";
            bool isPk = reader["IsPK"]?.ToString() == "1";

            columns.Add((name, type, nullable, isPk));
        }

        GenerateEntityClassFile(tableName, columns, isSqlServer: true);
    }

    private void GenerateDbContextFile(string tableName)
    {
        var sb = new StringBuilder();
        string formattedTableName =  ToPascalCase(tableName);
        
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("// Generated by CodeGenerator");
        sb.AppendLine($"// Timestamp: {DateTime.Now:yyyy-MM-dd}");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Data.Model.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace Data.Model;");
        sb.AppendLine();
        sb.AppendLine("public class AppDbContext : DbContext");
        sb.AppendLine("{");
        sb.AppendLine("     public DbSet<"+formattedTableName+"> "+tableName+" { get; set; }");
        sb.AppendLine("}");
        
        string outputDir = _config.GeneratorOutputPath;
        string filePath = Path.Combine(outputDir, "AppDbContext.cs");
        File.WriteAllText(filePath, sb.ToString());
    }
    
    private void GenerateEntityClassFile(
        string tableName,
        List<(string Name, string Type, bool Nullable, bool IsPrimaryKey)> columns,
        bool isSqlServer = false)
    {
        string outputDir = Path.Combine(_config.GeneratorOutputPath, "Models");
        
        string className = ToPascalCase(tableName);
        var sb = new StringBuilder();

        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("// Generated by CodeGenerator");
        sb.AppendLine($"// Timestamp: {DateTime.Now:yyyy-MM-dd}");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("//////////////////////////////////////////");
        sb.AppendLine("using System;");
        if (columns.Any(c => c.IsPrimaryKey || !c.Nullable))
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine();
        sb.AppendLine("namespace Data.Model.Models;");
        sb.AppendLine();
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        foreach (var col in columns)
        {
            if (col.IsPrimaryKey)
                sb.AppendLine("    [Key]");
            else if (!col.Nullable)
                sb.AppendLine("    [Required]");

            string csharpType = MapDbTypeToCSharp(col.Type, col.Nullable, isSqlServer);
            string propName = ToPascalCase(col.Name);

            sb.AppendLine($"    public {csharpType} {propName} {{ get; set; }}");
        }

        sb.AppendLine("}");

        string filePath = Path.Combine(outputDir, className + ".cs");
        File.WriteAllText(filePath, sb.ToString());

        _logger.Info($"Generated: {className}.cs");
    }

    private string MapDbTypeToCSharp(string dbType, bool isNullable, bool isSqlServer)
    {
        string type = dbType.ToUpper();

        if (isSqlServer)
        {
            return type switch
            {
                var t when t.Contains("INT") => isNullable ? "int?" : "int",
                var t when t.Contains("BIGINT") => isNullable ? "long?" : "long",
                var t when t.Contains("CHAR") || t.Contains("TEXT") || t.Contains("NCHAR") || t.Contains("NVARCHAR") => "string",
                var t when t.Contains("DECIMAL") || t.Contains("NUMERIC") => isNullable ? "decimal?" : "decimal",
                var t when t.Contains("DATE") || t.Contains("TIME") => isNullable ? "DateTime?" : "DateTime",
                var t when t.Contains("BIT") => isNullable ? "bool?" : "bool",
                var t when t.Contains("FLOAT") || t.Contains("REAL") => isNullable ? "double?" : "double",
                var t when t.Contains("BINARY") || t.Contains("VARBINARY") => "byte[]",
                _ => "string"
            };
        }
        else
        {
            // SQLite
            return type switch
            {
                var t when t.Contains("INT") => isNullable ? "int?" : "int",
                var t when t.Contains("CHAR") || t.Contains("CLOB") || t.Contains("TEXT") => "string",
                var t when t.Contains("REAL") || t.Contains("FLOA") || t.Contains("DOUB") => isNullable ? "double?" : "double",
                var t when t.Contains("BLOB") => "byte[]",
                var t when t.Contains("NUMERIC") => isNullable ? "decimal?" : "decimal",
                var t when t.Contains("DATE") => isNullable ? "DateTime?" : "DateTime",
                _ => "string"
            };
        }
    }

    private string ToPascalCase(string input)
    {
        return string.Concat(input.Split('_', ' ').Select(word => char.ToUpper(word[0]) + word.Substring(1).ToLower()));
    }
}